### ISSUE TITLE
Python version in Docker image

### ISSUE THREAD

**Issue by lezzidan** [bsc-wdc/dislib#113]
**Describe the bug**
The Python default in dislib image is 2; if I run something I get this error that shows the binding Python v2
 File "/opt/COMPSs/Bindings/python/2/pycompss/runtime/launch.py",

And the Python binary is pointing to Python 2

 ls -la /usr/bin/python
lrwxrwxrwx 1 root root 9 Nov 24  2017 /usr/bin/python -> python2.7

**Comment by kafkasl** [comment]
Dislib only works with python3+. 
The python default should always point to python2 because of OS assumptions. It can be changed with an alias or similar but it is not recommended. If you run from inside the docker pass always the argument `--python_interpreter=python3`. If you run with `dislib exec file.py` this is already done for you.
