### ISSUE TITLE
Codecov requirements discussion

### ISSUE THREAD

**Issue by salvisolamartinell** [bsc-wdc/dislib#131]
Sometimes it is convenient not to require a code-coverage:
- Exception handling of errors that are system dependent (cannot be reproduced with tests).
- Code for future developments (code that is not executed with the current code base, but could be executed after planned changes).
- Defensive coding in general (code that is not executed with the current code base, but could be executed after unplanned changes / if something breaks).

Requiring a code coverage like we do now is not agile:
- Pull requests that passed the codecov-project stop passing it because a merged pull request increased codecov-project, so after a rebase new commits and new reviews are required.
- Pull requests that remove lines and simplify code make codecov-project decrease, so the merge has to be forced.
- More pull requests pending to be merged means more rebases and makes the process tedious.

Proposal: require fixed codecov-project: 75%, codecov-patch: 85%. If codecov-project goes below 80% or we are missing tests then we can do a well-thought analysis of which tests we have to do.

Alternative: Allow programmers to mark some lines as *not coverage required*.

See stackoverflow discussion: https://stackoverflow.com/questions/90002/what-is-a-reasonable-code-coverage-for-unit-tests-and-why#90021

**Comment by javicid** [comment]
I agree with you in that aiming for 100% code coverage is probably not a good idea. However, I like the way it works right now, and I think 80-90% of coverage is easily achievable.

I understand the part about exception handling, this is something that can be included in the 10-20% of untested code. Do you have any examples of defensive code that shouldn't be tested?

Also, if I'm not mistaken, you can merge a PR that reduces the overall coverage as long as the new code is covered.

**Comment by kafkasl** [comment]
Answering the first 3 points:
* Could you provide some example of system dependent exceptions (probably I agree on this point, just want to make sure we are on the same page)
* I strongly advise against having unused code. It is always possible to create a branch a leave the changes there, or even better create a fork for youself. I am a big advocate of [KISS principle](https://en.wikipedia.org/wiki/KISS_principle)
* Again, I would rather not have defensive code (not too much at least) I some new changes break the code, better to now it ASAP with the tests instead of failing silently.

About the code coverage agile thing.
* If a review was aproved, and after rebasing the tests are OK it's fine to merge it anyway IMO.
* For the problems about **PR** which decrease codecov I believe the easiest way is just put a comment on the PR saying why that happens (e.g. I just removed code so it's normal) so the reviewer can just merge it anyways.
* Pending MR do not require rebase, only after they are merged. Anyways the tests last 3-4 min and we normally do not have that much PRs so I don't think it's that tedious.

In general the codecov PR problems should be just discussed/commented in the PR making it fast and flexible (we all understand that removing code it's fine even if it decreases codecov).

If you are fine with what I propose I'll close the issue, otherwise just reopen the issue @salvisolamartinell  @javicid
