### ISSUE TITLE
Improve shuffle with optimal subset sizes

### ISSUE THREAD

**Issue by javicid** [bsc-wdc/dislib#140]
The shuffle method can generate unbalanced subsets in some particular cases in which the number of subsets is large compared to the number of samples. 

For example, the shuffling performed in UtilsTest.test_shuffle_sparse (in tests/test_utils.py) generates 6 subsets of sizes 13, 12, 12, 6, 6, 6. This is due to the way samples are partitioned during the shuffling process. This process could be improved by computing the partitioning of a subset into N new subsets that minimizes the difference in size of the N resulting subsets, which is essentially the _partition problem_.

I couldn't find an implementation of the problem in scipy.

More info about the problem to solve: https://stackoverflow.com/questions/22519470/calculate-set-partitions-with-specific-subset-sizes

**Comment by salvisolamartinell** [comment]
I've thought of multiple options if we want the shuffled dataset to have balanced subsets:

**Options**
1. Shuffling as now and then rebalancing the subsets by collecting the subset sizes and transferring the differences.
2.  Precomputing in the master the partitions (sampling (multivariate-)hypergeometric probability distributions sequentially).
3. Shuffling each subset and transferring to each new subset a fixed-size subsample. (This can be done avoiding unbalance.)

**Problems:**
Option 1: Big subsets could overflow a node's memory. The number of transfers could be more than theoretically needed.
Option 2: There is more sequential work in the master, it could be a limitation for scaling to a large number of nodes.
Option 3: Not a real random shuffle, elements in a subset are certainly separated. If we do 2 iterations of the same approach, the shuffle looks real, but the transfers are double.

I suggest option number 3 because it scales better. The docs should explain how it works, warn that it's not as random as a local implementation would be, and explain that for ensemble methods it's better to use it iteratively, not from the original dataset every time.

**Comment by javicid** [comment]
Currently shuffle is doing option 3 if I'm not mistaken. The only thing that is left is to ensure that the sizes of the resulting subsets are balanced.

**Comment by salvisolamartinell** [comment]
I see, I thought it was randomly choosing the new subset for each sample.

I think this line may be wrong:
dislib/dislib/utils/base.py, line 92: `sample_size = max(1, int(subset_size / n_subsets))`

But anyways, to balance the subsets we have to rewrite this part.

**Comment by javicid** [comment]
> But anyways, to balance the subsets we have to rewrite this part.

That's what I thought.
