### ISSUE TITLE
pip pycompss dependency

### ISSUE THREAD

**Issue by nmilosev** [bsc-wdc/dislib#190]
Hello there,

I would like to ask if there is a specific reason why pycompss isn't listed as a hard dependency in the setup.py file?

It could be a good idea to add it, as of now if you install dislib it will not pull pycompss with itself and then it will immediately complain about a missing `pycompss` module which could be confusing to some users.

Just a suggestion. :)

Cheers!

**Comment by javicid** [comment]
Hi @nmilosev!

This is a very good question, and it is something that we discussed when we created the pip package. 

We chose not to list pycompss as a dependency because there are several ways in which you can install PyCOMPSs, and some of these ways do not make the `pycompss` module visible at installation time. For example, if PyCOMPSs is installed "manually" in certain supercomputers, the `pycompss` module is only visible at run time. We didn't want to get pip errors when installing dislib in these scenarios.

Were you following the quickstart guide when you had this problem? I am asking because maybe we should make this point more clear to users.

**Comment by nmilosev** [comment]
Hello @javicid thank you for your quick response.

We are also using it on our cluster (I'm from UNSPMF and we are using dislib as a part of I-BiDaaS project) and everything works fine. This is just an issue I ran into when installing dislib locally for development.

I think it's a great idea to include a note of some sort in the quickstart document (which is very good already).

Thanks!

PS. Can we include our cluster on your list? :) The entry would be:

- Axiom - University of Novi Sad, Faculty of Sciences (UNSPMF)

**Comment by javicid** [comment]
That's great! I will add the note in the guide, and your cluster to the list! Thank you for the suggestion :)

I'm closing this issue, feel free to open new ones if you run into other errors or if you have any other suggestion.

**Comment by nmilosev** [comment]
Sure, thanks! :)
